name: unit-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v2

    # set up our environment
    - 
      name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    -
      name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    # run the library's tests
    -
      name: run tests
      env:
        pyver: ${{ matrix.python-version }}
      run: tox -e py${pyver//./}

  # if all the tests pass on a push to main,
  # publish the new code to pypi
  publish:
    runs-on: ubuntu-latest
    needs: test
    environment: PyPI
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2
    - 
      name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.16
      with:
        python_version: "3.10.9"
        pypi_token: ${{ secrets.PYPI_TOKEN }}
